version: '3.9'

services:
  goods:
    image: goods-api:latest
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile-local
    ports:
      - "3002:8002"
    environment:
      - PORT=8002
      - NODE_ENV=local
    restart: always
    networks:
      - msa-api-network

networks:
  msa-api-network: